<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Pocket.Logger\Core\Formatter.cs" Link="%28Pocket%29\Formatter.cs" />
    <Compile Include="..\Pocket.Logger\Core\Logger.cs" Link="%28Pocket%29\Logger.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="%28Pocket%29\" />
  </ItemGroup>

</Project>